FROM docker.io/library/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d AS builder
RUN apk add --no-cache \
    icu-libs \
    sqlite-static \
    yaml-static \
    yaml-dev \
    libxml2-static \
    zlib-static \
    openssl-libs-static \
    openssl-dev \
    musl-dev \
    xz-static \
    gcc \
    pcre2-dev \
    gc-dev \
    libevent-dev

WORKDIR /invidious

ARG INVIDIOUS
COPY ${INVIDIOUS} ./
ARG BUILDLOG
COPY ${BUILDLOG} ./

RUN $(tail -n1 buildlog)