FROM docker.io/library/alpine:3.18.5@sha256:34871e7290500828b39e22294660bee86d966bc0017544e848dd9a255cdf59e0 AS builder
RUN apk add --no-cache 'crystal=1.8.2-r0' \
    shards \
    sqlite-static \
    yaml-static \
    yaml-dev \
    libxml2-static \ 
    zlib-static \
    openssl-libs-static \
    openssl-dev \
    musl-dev \
    xz-static

WORKDIR /invidious
COPY shard.yml shard.lock ./
RUN shards install

COPY . .

ARG release=1
RUN crystal spec --release \
    --warnings all \
    --link-flags "-lxml2 -llzma"   
RUN if [ "$release" == 1 ] ; then \
        crystal build ./src/invidious.cr \
        --release \
        --warnings all \
        --link-flags "-lxml2 -llzma"; \
    else \
        crystal build ./src/invidious.cr \
        --warnings all \
        --link-flags "-lxml2 -llzma"; \
    fi

FROM docker.io/library/alpine:3.18.5@sha256:34871e7290500828b39e22294660bee86d966bc0017544e848dd9a255cdf59e0 AS release
RUN apk add --no-cache rsvg-convert ttf-opensans tini gc yaml libevent
WORKDIR /invidious
RUN addgroup -g 1000 -S invidious && \
    adduser -u 1000 -S invidious -G invidious

# Copy config
COPY --chown=invidious config/config.example.yml config/config.yml
RUN sed -i 's/host: \(127.0.0.1\|localhost\)/host: invidious-db/' config/config.yml

# Get invidious
COPY --from=builder /invidious/invidious ./
COPY --from=builder /invidious/assets assets
COPY --from=builder /invidious/locales locales
COPY --from=builder /invidious/config/sql config/sql
RUN chmod o+rX -R ./assets ./config ./locales

EXPOSE 3000
USER invidious

ENTRYPOINT ["/sbin/tini", "--"]
CMD [ "/invidious/invidious" ]