name: Build and Test Docker Images

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 03 * * *'  # 3:20am everyday

jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        containerdistro: [ alpine, debian, centos ]
        arches: [ linux/amd64, linux/arm64, linux/arm/v7, linux/ppc64le ]
        patchsets: [ vanilla, highload, redis ]
        exclude:
          - containerdistro: debian
            arches: linux/arm64
          - containerdistro: debian
            arches: linux/arm/v7
          - containerdistro: debian
            arches: linux/ppc64le
          - containerdistro: centos
            arches: linux/arm64
          - containerdistro: centos
            arches: linux/arm/v7
          - containerdistro: centos
            arches: linux/ppc64le
        include:
          - arches: linux/amd64
            arch-tag: amd64
          - arches: linux/arm64
            arch-tag: arm64
          - arches: linux/arm/v7
            arch-tag: armv7
          - arches: linux/ppc64le
            arch-tag: ppc64le

    permissions:
      contents: read
      packages: write
      security-events: write

    name: Docker Images
    steps:

      # SETUP

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
            submodules: recursive

      # PREPARE

      - name: Get patches
        run: |
          chmod u+x scripts/*
          ./scripts/get-patches.sh
          ./scripts/apply-patches.sh ${{ matrix.patchsets }}
          ./scripts/fix-git-compile.sh

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          # Generate a timestamp for creating an image version history
          TIMESTAMP="$(date +%Y%m%d)"
          VARIANT="${{ matrix.containerdistro }}"

          COMMIT_TAGS=()
          BUILD_TAGS=()

          if [[ "${{ matrix.containerdistro }}" == "alpine" ]]; then
            if [[ "${{ matrix.patchsets }}" == "vanilla" ]]; then
              BUILD_TAGS+=("latest")
              BUILD_TAGS+=("latest-${{ matrix.arch-tag }}")
              BUILD_TAGS+=("alpine")
              BUILD_TAGS+=("alpine-${{ matrix.arch-tag }}")
            elif [[ "${{ matrix.patchsets }}" == "highload" ]]; then
              BUILD_TAGS+=("latest-highload")
              BUILD_TAGS+=("latest-highload-${{ matrix.arch-tag }}")
              BUILD_TAGS+=("alpine-highload")
              BUILD_TAGS+=("alpine-highload-${{ matrix.arch-tag }}")
            elif [[ "${{ matrix.patchsets }}" == "redis" ]]; then
              BUILD_TAGS+=("latest-redis")
              BUILD_TAGS+=("latest-redis-${{ matrix.arch-tag }}")
              BUILD_TAGS+=("alpine-redis")
              BUILD_TAGS+=("alpine-redis-${{ matrix.arch-tag }}")
            fi 
          elif [[ "${{ matrix.containerdistro }}" == "debian" ]]; then
            if [[ "${{ matrix.patchsets }}" == "vanilla" ]]; then
              BUILD_TAGS+=("debian")
              BUILD_TAGS+=("debian-${{ matrix.arch-tag }}")
            elif [[ "${{ matrix.patchsets }}" == "highload" ]]; then
              BUILD_TAGS+=("debian-highload")
              BUILD_TAGS+=("debian-highload-${{ matrix.arch-tag }}")
            elif [[ "${{ matrix.patchsets }}" == "redis" ]]; then
              BUILD_TAGS+=("debian-redis")
              BUILD_TAGS+=("debian-redis-${{ matrix.arch-tag }}")
            fi
          elif [[ "${{ matrix.containerdistro }}" == "centos" ]]; then
            if [[ "${{ matrix.patchsets }}" == "vanilla" ]]; then
              BUILD_TAGS+=("centos")
              BUILD_TAGS+=("centos-${{ matrix.arch-tag }}")
            elif [[ "${{ matrix.patchsets }}" == "highload" ]]; then
              BUILD_TAGS+=("centos-highload")
              BUILD_TAGS+=("centos-highload-${{ matrix.arch-tag }}")
            elif [[ "${{ matrix.patchsets }}" == "redis" ]]; then
              BUILD_TAGS+=("centos-redis")
              BUILD_TAGS+=("centos-redis-${{ matrix.arch-tag }}")
            fi
          fi
          

          # Append matching timestamp tags to keep a version history
          for TAG in "${BUILD_TAGS[@]}"; do
              BUILD_TAGS+=("${TAG}-${TIMESTAMP}")
          done

          echo "Generated the following build tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done

          alias_tags=("${BUILD_TAGS[@]}")
          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT

      - name: Get the last (and most specific) tag
        id: specific-tag
        run: |
          echo "super_specific_tag=$(echo ${{ steps.generate-tags.outputs.alias_tags }} | awk '{print $NF}')" >> $GITHUB_OUTPUT

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-user-static
          version: 1.0

      - name: Cache Shards
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/shardscache
          key: shards-${{ hashFiles('invidious/shard.lock') }}

      # BUILD

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: invidious
          tags: ${{ steps.generate-tags.outputs.alias_tags }}
          containerfiles: Dockerfile.${{ matrix.containerdistro }}
          platforms: ${{ matrix.arches }}
          extra-args: |
            --volume=${{ github.workspace }}/shardscache:/invidious/lib
            --cache-from=ghcr.io/${{ github.repository_owner }}/invidious
          context: invidious


      # PUSH

      - name: Push To GHCR
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}

      # SIGN

      - uses: sigstore/cosign-installer@v3.1.2

      - name: Sign GHCR Image
        run:  |
          cosign login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}@${GHCR_TAGS}
        env:
          COSIGN_EXPERIMENTAL: false
          GHCR_TAGS: ${{ steps.push-to-ghcr.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      # SCAN

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:${{ steps.specific-tag.outputs.super_specific_tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      # PRINT

      - name: Print image URLs
        run:  |
          echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
