name: Build and Test Docker Images

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 03 * * *'  # 3:20am everyday

jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        containerdistro: [ alpine, min, debian, ubuntu, centos ]
        arches: [ linux/amd64, linux/arm64, linux/arm/v7, linux/ppc64le ]
        patchsets: [ vanilla, highload, redis ]
        exclude:
          - containerdistro: debian
            arches: linux/arm64
          - containerdistro: debian
            arches: linux/arm/v7
          - containerdistro: debian
            arches: linux/ppc64le
          - containerdistro: ubuntu
            arches: linux/arm64
          - containerdistro: ubuntu
            arches: linux/arm/v7
          - containerdistro: ubuntu
            arches: linux/ppc64le
          - containerdistro: centos
            arches: linux/arm64
          - containerdistro: centos
            arches: linux/arm/v7
          - containerdistro: centos
            arches: linux/ppc64le

        include:
          - arches: linux/amd64
            arch-tag: amd64
          - arches: linux/arm64
            arch-tag: arm64
          - arches: linux/arm/v7
            arch-tag: armv7
          - arches: linux/ppc64le
            arch-tag: ppc64le

    permissions:
      contents: read
      packages: write
      security-events: write

    name: Docker Images
    steps:

      # SETUP

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
            submodules: recursive

      # PREPARE

      - name: Get patches
        run: |
          chmod u+x scripts/*
          ./scripts/get-patches.sh
          ./scripts/apply-patches.sh ${{ matrix.patchsets }}
          ./scripts/fix-git-compile.sh

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          scripts/generate-tags.sh ${{ matrix.containerdistro }} ${{ matrix.patchsets }} ${{ matrix.arches }}
          alias_tags=("${BUILD_TAGS[@]}")
          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT

      # - name: Get the last (and most specific) tag
      #   id: specific-tag
      #   run: |
      #     echo "super_specific_tag=$(echo ${{ steps.generate-tags.outputs.alias_tags }} | awk '{print $NF}')" >> $GITHUB_OUTPUT

      - name: Install packages for testing
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static podman

      - name: Cache Shards
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/shardscache
          key: shards-${{ hashFiles('invidious/shard.lock') }}

      # Ensure shardscache exists
      - run: mkdir -p ${{ github.workspace }}/shardscache

      # BUILD

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: invidious
          tags: ${{ steps.generate-tags.outputs.alias_tags }}
          containerfiles: Dockerfile.${{ matrix.containerdistro }}
          platforms: ${{ matrix.arches }}
          extra-args: |
            --volume=${{ github.workspace }}/shardscache:/invidious/lib
            --cache-from=ghcr.io/${{ github.repository_owner }}/invidious
          context: invidious

      # TEST
      - name: Test image
        if: matrix.arch-tag == 'amd64'
        run: ./scripts/test-image.sh ${{ steps.build-image.outputs.image }}

      # PUSH

      - name: Push To GHCR
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}

      # SIGN

      - uses: sigstore/cosign-installer@v3.1.2

      - name: Sign GHCR Image
        run:  |
          cosign login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}@${{ steps.push-to-ghcr.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      # SCAN

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}@${{ steps.push-to-ghcr.outputs.digest }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      # PRINT

      - name: Print image URLs
        run:  |
          echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
