name: Build Final Invidious Binaries

on: 
  workflow_call:
    inputs:
      patchset:
        description: 'Patchset to build'
        required: true
        type: string
      crystalversion:
        description: 'Crystal version to build'
        required: true
        type: string
      targettriple:
        description: 'Target triple to build'
        required: true
        type: string
      targetplatform:
        description: 'Target platform to build'
        required: true
        type: string

jobs:
  final_build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Get Initial Build Artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: initial-invidious-${{ inputs.patchset }}-${{ inputs.crystalversion }}-${{ inputs.targettriple }}
      
      - name: Sanity Check
        run: ls -la

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

      # - name: Build Invidious Binaries
      #   run: |
      #     docker run -i -v $PWD:/workspace -w /workspace --rm docker.io/multiarch/alpine:aarch64-edge \
      #       /bin/sh -c "echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/community' >>/etc/apk/repositories && \
      #       apk add --update --no-cache --force-overwrite icu-libs sqlite-static yaml-static yaml-dev libxml2-static zlib-static openssl-libs-static openssl-dev musl-dev xz-static gcc pcre2-dev gc-dev libevent-dev && \
      #       $(tail -n1 buildlog)"

      - name: Build and push
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: .
          platforms: ${{ inputs.targetplatform }}
          outputs: type=local,dest=invidious
          build-args: |
            INVIDIOUS=invidious.o
            BUILDLOG=buildlog

      - name: Upload Final Binary
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: invidious-${{ inputs.patchset }}-${{ inputs.crystalversion }}-${{ inputs.targettriple }}
          path: ./invidious