name: Build Final Invidious Binaries

on: 
  workflow_call:
    inputs:
      patchset:
        description: 'Patchset to build'
        required: true
        type: string
      crystalversion:
        description: 'Crystal version to build'
        required: true
        type: string
      targettriple:
        description: 'Target triple to build'
        required: true
        type: string
      targetplatform:
        description: 'Target platform to build'
        required: true
        type: string

jobs:
  final_build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Get Initial Build Artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          name: initial-invidious-${{ inputs.patchset }}-${{ inputs.crystalversion }}-${{ inputs.targettriple }}
      
      - name: Sanity Check
        run: ls -la

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      # - name: Build Invidious Binaries
      #   run: |
      #     docker run -i -v $PWD:/workspace -w /workspace --rm docker.io/multiarch/alpine:aarch64-edge \
      #       /bin/sh -c "echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/community' >>/etc/apk/repositories && \
      #       apk add --update --no-cache --force-overwrite icu-libs sqlite-static yaml-static yaml-dev libxml2-static zlib-static openssl-libs-static openssl-dev musl-dev xz-static gcc pcre2-dev gc-dev libevent-dev && \
      #       $(tail -n1 buildlog)"

      - name: Build and push
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6
        with:
          context: .
          platforms: ${{ inputs.targetplatform }}
          outputs: type=local,dest=invidious
          build-args: |
            INVIDIOUS=invidious.o
            BUILDLOG=buildlog

      - name: Upload Final Binary
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: invidious-${{ inputs.patchset }}-${{ inputs.crystalversion }}-${{ inputs.targettriple }}
          path: ./invidious