name: Build Initial Invidious Binaries

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 03 * * *'  # 3:20am everyday

jobs:
  build_invidious: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystalversions: [ "1.9", "1.8" ]
        triple: [ aarch64-unknown-linux-musl, x86_64-unknown-linux-musl ]
        patchsets: [ vanilla ]
        include:
          - crystalversions: "1.8"
            is_supported: true
          - triple: "aarch64-unknown-linux-musl"
            platform: "linux/arm64"
          - triple: "x86_64-unknown-linux-musl"
            platform: "linux/amd64"


    permissions:
      packages: write

    container:
      image: docker.io/crystallang/crystal:${{ matrix.crystalversions }}-alpine

    steps:

      # INSTALL TOOLS AND DEPENDENCIES

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystalversions }}

      - name: Install dependencies
        run: |
          sudo apt install -y curl git bash sqlite-static yaml-static

      # CHECKOUT

      - name: Check out the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: recursive

      # PREPARE

      - name: Get patches
        run: |
          chmod u+x scripts/*
          ./scripts/get-patches.sh
          ./scripts/apply-patches.sh ${{ matrix.patchsets }}

      - name: Cache Shards
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: ./invidious/lib
          key: shards-${{ hashFiles('invidious/shard.lock') }}

      - name: Install shards
        run: |
          shards install
        working-directory: ./invidious

      # BUILD

      - name: Cross-compile
        run: |
          crystal build ./src/invidious.cr \
            --static \
            --release \
            --warnings all \
            --cross-compile --target "${{ matrix.triple }}" \
            --link-flags "-lxml2 -llzma" | tee buildlog
        working-directory: ./invidious

      # UPLOAD

      - name: Upload binaries
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: initial-invidious-${{ matrix.patchsets }}-${{ matrix.crystalversions }}-${{ matrix.triple }}
          path: |
            ./invidious/buildlog
            ./invidious/invidious.o
  
      # CALL
      - name: Call finish_build.yml
        uses: np22-jpg/invidious/.github/workflows/finish_build.yml@main
        with:
          crystalversion: ${{ matrix.crystalversions }}
          targettriple: ${{ matrix.triple }}
          targetplatform: ${{ matrix.platform }}
          patchset: ${{ matrix.patchsets }}
