name: Build and Upload Static Invidious Binaries

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 03 * * *'  # 3:20am everyday

jobs:
  build_invidious: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystalversions: [ "1.9", "1.8" ]
        triple: [ aarch64-unknown-linux-musl, x86_64-unknown-linux-musl ]
        patchsets: [ vanilla, redis ]
        include:
          - crystalversions: "1.8"
            is_supported: true

    permissions:
      packages: write

    steps:

      # INSTALL TOOLS AND DEPENDENCIES

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystalversions }}

      - name: Install dependencies
        run: |
          sudo apt install -y curl git

      # CHECKOUT

      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive

      # PREPARE

      - name: Get patches
        run: |
          chmod u+x scripts/*
          ./scripts/get-patches.sh
          ./scripts/apply-patches.sh ${{ matrix.patchsets }}

      - name: Cache Shards
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ./invidious/lib
          key: shards-${{ hashFiles('invidious/shard.lock') }}

      - name: Install shards
        run: |
          shards install
        working-directory: ./invidious

      # CHECK

      - name: Unit test
        if: matrix.triple == 'x86_64-unknown-linux-musl'
        run: |
          sudo podman run -i -v `pwd`:/workspace -w /workspace --rm crystallang/crystal:${{ matrix.crystalversions }}-alpine \
            sh -c "apk add --no-cache sqlite-static yaml-static && \
            crystal spec --release \
            --warnings all \
            --link-flags '-lxml2 -llzma'"
        working-directory: ./invidious

      # BUILD

      - name: Compile
        if: matrix.triple == 'x86_64-unknown-linux-musl'
        run: |
          sudo podman run -i -v `pwd`:/workspace -w /workspace --rm crystallang/crystal:${{ matrix.crystalversions }}-alpine \
            sh -c "apk add --no-cache sqlite-static yaml-static && \
            crystal build ./src/invidious.cr \
            --static \
            --release \
            --warnings all \
            --link-flags '-lxml2 -llzma'"; 
        working-directory: ./invidious

      - name: Cross-compile
        if: matrix.triple != 'x86_64-unknown-linux-musl'
        run: |
          final_command=$(crystal build ./src/invidious.cr \
          --static \
          --release \
          --warnings all \
          --cross-compile --target "${{ matrix.triple }}" \
          --link-flags "-lxml2 -llzma" | tail -1) 
          sudo podman run -i -v `pwd`:/workspace -w /workspace --rm docker.io/multiarch/alpine:aarch64-edge \
            /bin/sh -c "echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/community' >>/etc/apk/repositories && \
            apk add --update --no-cache --force-overwrite icu-libs sqlite-static yaml-static yaml-dev libxml2-static zlib-static openssl-libs-static openssl-dev musl-dev xz-static gcc pcre2-dev gc-dev libevent-dev && \
            $final_command"
        working-directory: ./invidious

      # UPLOAD

      - name: Upload binaries
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: invidious-${{ matrix.patchsets }}-${{ matrix.crystalversions }}-${{ matrix.triple }}
          path: ./invidious/invidious