name: Build and Upload Static Invidious Binaries

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 03 * * *'  # 3:20am everyday

jobs:
  build_invidious: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystalversions: [ 1.9, 1.8, 1.7, 1.7, 1.5, 1.4 ]
        triple: [ aarch64-unknown-linux-musl, x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf ]
        patchsets: [ vanilla, highload, redis ]
        include:
          - crystalversions: 1.9
            is_latest: true

    container:
      image: docker.io/library/alpine:latest

    permissions:
      packages: write

    steps:

      # CHECKOUT

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
            submodules: recursive

      # INSTALL CRYSTAL AND DEPENDENCIES

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystalversions }}

      - name: Install dependencies
        run: |
          apk add \
          shards \
          sqlite-static \
          yaml-static \
          yaml-dev \
          libxml2-static \ 
          zlib-static \
          openssl-libs-static \
          openssl-dev \
          musl-dev \
          xz-static

      # PREPARE

      - name: Get patches
        run: |
          chmod u+x scripts/*
          ./scripts/get-patches.sh
          ./scripts/apply-patches.sh ${{ matrix.patchsets }}
          ./scripts/fix-git-compile.sh

      - name: Install shards
        run: |
          cd ${{ github.workspace }}/invidious
          shards install

      # CHECK

      - name: Unit test
        run: |
          cd ${{ github.workspace }}/invidious
          crystal spec --release \
          --warnings all \
          --cross-compile --target "${{ matrix.triple }}" \
          --link-flags "-lxml2 -llzma"

      # BUILD

      - name: Compile
        run: |
          cd ${{ github.workspace }}/invidious
          crystal build ./src/invidious.cr \
          --static \
          --release \
          --warnings all \
          --cross-compile --target "${{ matrix.triple }}" \
          --link-flags "-lxml2 -llzma"; 

      # UPLOAD

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: invidious-${{ matrix.patchsets }}-${{ matrix.crystalversions }}-${{ matrix.triple }}
          path: ${{ github.workspace }}/invidious/invidious